#define BINDING_PARTICLES 0
#define BINDING_DENSITIES 1
#define BINDING_PREDICTED_POSITIONS 2
#define BINDING_CONFIG 3
#define BINDING_SIMULATION 4
#define BINDING_START_CHUNKS 5
#define BINDING_PAIRS 6
#define BINDING_EXISTENCE_FIELD 7

#define LOCATION_POS 0
#define LOCATION_VELO 1


